# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kryptosuser',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('answer', models.CharField(max_length=250)),
                ('level_image', models.ImageField(upload_to='level_images/')),
            ],
        ),
    ]
