# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('profile_picture', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
