# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 04:13
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=10)),
                ('buy_ss', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Old_Stock_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=10)),
                ('buy_ss', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cash_bal', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=19)),
                ('net_worth', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('no_trans', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_data',
            fields=[
                ('symbol', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('high', models.DecimalField(decimal_places=2, max_digits=19)),
                ('low', models.DecimalField(decimal_places=2, max_digits=19)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('change', models.DecimalField(decimal_places=2, max_digits=19)),
                ('change_per', models.DecimalField(decimal_places=2, max_digits=19)),
                ('trade_Qty', models.DecimalField(decimal_places=2, max_digits=19)),
                ('trade_Value', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=10)),
                ('buy_ss', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
