# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalalbull', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old_stock_data',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stock_data',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stock_data',
            name='change_per',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stock_data',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stock_data',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stock_data',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stock_data',
            name='open_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stock_data',
            name='trade_Qty',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stock_data',
            name='trade_Value',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
