# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bblevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelId', models.IntegerField(default=1)),
                ('qnId', models.IntegerField(default=1)),
                ('qnDesc', models.CharField(max_length=500)),
                ('qnAns', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='bbplayer',
            fields=[
                ('playerId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('playerLevel', models.IntegerField(default=0)),
                ('playerQn', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bblevel',
            unique_together=set([('levelId', 'qnId')]),
        ),
    ]
